### ISSUE TITLE
Crash with Sinatra 2.0: `undefined method <<`

### ISSUE THREAD

**Issue by MarcusRiemer** [fnando/sinatra-subdomain#14]
This code crashes for me **precisely** at the `subdomain` call. I have attached the Stacktrace, [the line 412 in question is available here](https://bitbucket.org/marcusriemer/esqulino/src/a08c0a85e2096b540d10779893b9ab9ff7e91bef/server/main.rb?at=master&fileviewer=file-view-default#main.rb-412).

    NoMethodError: undefined method `<<' for #<Proc:0x00000002fd6180>
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-subdomain-0.2.0/lib/sinatra/subdomain.rb:57:in `route_added'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1608:in `block in invoke_hook'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1608:in `each'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1608:in `invoke_hook'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1603:in `route'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-contrib-2.0.0/lib/sinatra/multi_route.rb:73:in `block (2 levels) in route'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-contrib-2.0.0/lib/sinatra/multi_route.rb:72:in `each'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-contrib-2.0.0/lib/sinatra/multi_route.rb:72:in `block in route'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-contrib-2.0.0/lib/sinatra/multi_route.rb:70:in `each'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-contrib-2.0.0/lib/sinatra/multi_route.rb:70:in `route'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1383:in `get'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-contrib-2.0.0/lib/sinatra/multi_route.rb:61:in `get'
      server/main.rb:415:in `block in <class:ScratchSqlApp>'
      server/vendor/bundle/ruby/2.4.0/gems/sinatra-subdomain-0.2.0/lib/sinatra/subdomain.rb:28:in `subdomain'
      server/main.rb:412:in `<class:ScratchSqlApp>'
      server/main.rb:28:in `<top (required)>'

The exact dependencies this crashes with are:

    GEM
      remote: https://rubygems.org/
      specs:
        addressable (2.5.1)
          public_suffix (~> 2.0, >= 2.0.2)
        backports (3.8.0)
        daemons (1.2.4)
        eventmachine (1.2.3)
        ffi (1.9.18)
        ffi-compiler (1.0.1)
          ffi (>= 1.0.0)
          rake
        json-schema (2.8.0)
          addressable (>= 2.4)
        liquid (4.0.0)
        listen (3.1.5)
          rb-fsevent (~> 0.9, >= 0.9.4)
          rb-inotify (~> 0.9, >= 0.9.7)
          ruby_dep (~> 1.2)
        multi_json (1.12.1)
        mustermann (1.0.0)
        public_suffix (2.0.5)
        rack (2.0.3)
        rack-protection (2.0.0)
          rack
        rake (12.0.0)
        rb-fsevent (0.9.8)
        rb-inotify (0.9.8)
          ffi (>= 0.5.0)
        rerun (0.11.0)
          listen (~> 3.0)
        ruby_dep (1.5.0)
        scrypt (3.0.5)
          ffi-compiler (>= 1.0, < 2.0)
        sinatra (2.0.0)
          mustermann (~> 1.0)
          rack (~> 2.0)
          rack-protection (= 2.0.0)
          tilt (~> 2.0)
        sinatra-contrib (2.0.0)
          backports (>= 2.0)
          multi_json
          mustermann (~> 1.0)
          rack-protection (= 2.0.0)
          sinatra (= 2.0.0)
          tilt (>= 1.3, < 3)
        sinatra-subdomain (0.2.0)
          sinatra
        sqlite3 (1.3.13)
        thin (1.7.0)
          daemons (~> 1.0, >= 1.0.9)
          eventmachine (~> 1.0, >= 1.0.4)
          rack (>= 1, < 3)
        tilt (2.0.7)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      json-schema
      liquid
      rerun
      scrypt
      sinatra
      sinatra-contrib
      sinatra-subdomain
      sqlite3
      thin
    
    BUNDLED WITH
       1.14.6

**Comment by fnando** [comment]
Just released v0.2.1, which fix this issue.

**Comment by MarcusRiemer** [comment]
This indeed fixes it, thanks for the speedy reaction!
